### PR TITLE
fix: update Gatsby peer dependency for Gatsby 4

### PR DESCRIPTION
**Pull request by LuisOsta**
I've upgraded the version of Gatsby that the addon uses to v4.1.2
## Types of changes

- [x] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
In order for applications using the latest version of Gatsby to utilize this addon, this package needs to be upgraded to use the latest version of Gatsby as well. The version of Gatsby was set to the latest 4.X one.

## Checklist:

- [ ] My change requires an update to the official documentation.
- [ ] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by LuisOsta** [comment]
@angeloashmore Let me know if anything is missing from the PR

**Comment by angeloashmore** [comment]
@LuisOsta Thanks! Maybe we could use this instead to support Gatsby 3 and 4?

```
"gatsby": "^3 || ^4"
```

Do you have time to do a quick test to see if that works for both Gatsby 3 and 4 projects?

**Comment by LuisOsta** [comment]
@angeloashmore I'll give it a try! Might take me a bit as I've never used a fork as a package but I'll figure it out

**Comment by angeloashmore** [comment]
Thanks! If you aren't able to test it out, no worries. I can give it a try later as well. :)

**Comment by LuisOsta** [comment]
I'd really appreciate if you did as I'm still trying to get it to work lol. I'll see if I can finish it but it may very well be faster if you do it

**Comment by LuisOsta** [comment]
@angeloashmore Any updates?

**Comment by angeloashmore** [comment]
Hey @LuisOsta, sorry, I haven’t had a chance yet. I should have time to try on Monday. 👍

**Comment by angeloashmore** [comment]
Hey @LuisOsta, looks like it's all good! Thanks for the PR! 🙂

**Comment by LuisOsta** [comment]
I'm happy to contribute and thank you for the quick test!

**Pull request merged**
